import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docsSidebar: [
        "index",
        {
            type: "category",
            label: "指南",
            items: ["guide/quick-start", "guide/ai-usage"],
        },
        {
            type: "category",
            label: "组件",
            items: [
                "components/overview",
                {
                    type: "category",
                    label: "通用",
                    items: [
                        { type: "doc", id: "components/general", label: "总览" },
                        "components/general/button",
                        "components/general/typography",
                    ],
                },
                {
                    type: "category",
                    label: "布局",
                    items: [
                        { type: "doc", id: "components/layout", label: "总览" },
                        "components/layout/stack",
                        "components/layout/inline",
                        "components/layout/compact",
                        "components/layout/toolbar",
                        "components/layout/scroll-area",
                        "components/layout/separator",
                        "components/layout/split-pane",
                    ],
                },
                {
                    type: "category",
                    label: "导航",
                    items: [
                        { type: "doc", id: "components/navigation", label: "总览" },
                        "components/navigation/breadcrumb",
                        "components/navigation/pagination",
                        "components/navigation/tabs",
                        "components/navigation/segmented",
                        "components/navigation/tree",
                        "components/navigation/dropdown",
                        "components/navigation/menu",
                        "components/navigation/command",
                        "components/navigation/tooltip",
                        "components/navigation/accordion",
                        "components/navigation/collapsible",
                    ],
                },
                {
                    type: "category",
                    label: "数据录入",
                    items: [
                        { type: "doc", id: "components/data-entry", label: "总览" },
                        "components/data-entry/input",
                        "components/data-entry/search-input",
                        "components/data-entry/password-input",
                        "components/data-entry/textarea",
                        "components/data-entry/number-input",
                        "components/data-entry/select",
                        "components/data-entry/combobox",
                        "components/data-entry/checkbox",
                        "components/data-entry/radio-group",
                        "components/data-entry/switch",
                        "components/data-entry/slider",
                        "components/data-entry/date-picker",
                        "components/data-entry/upload",
                        "components/data-entry/form",
                        "components/data-entry/field",
                        "components/data-entry/field-group",
                        "components/data-entry/form-section",
                        "components/data-entry/form-actions",
                    ],
                },
                {
                    type: "category",
                    label: "数据展示",
                    items: [
                        { type: "doc", id: "components/data-display", label: "总览" },
                        "components/data-display/table",
                        "components/data-display/descriptions",
                        "components/data-display/list",
                        "components/data-display/card",
                        "components/data-display/tag",
                        "components/data-display/badge",
                        "components/data-display/statistic",
                        "components/data-display/timeline",
                    ],
                },
                {
                    type: "category",
                    label: "反馈",
                    items: [
                        { type: "doc", id: "components/feedback", label: "总览" },
                        "components/feedback/alert",
                        "components/feedback/empty",
                        "components/feedback/loading",
                        "components/feedback/progress",
                        "components/feedback/dialog",
                        "components/feedback/drawer",
                        "components/feedback/confirm",
                        "components/feedback/toast",
                        "components/feedback/notification",
                    ],
                },
                {
                    type: "category",
                    label: "其他",
                    items: [
                        { type: "doc", id: "components/media-other", label: "总览" },
                        "components/media-other/avatar",
                        "components/media-other/image",
                    ],
                },
                "components/patterns",
                "components/recipes",
            ],
        },
    ],
};

export default sidebars;
